"""AutoDJ offline analysis worker stub."""

__version__ = "0.1.0"

from .analyze import analyze_stub, build_analyzed_track_stub
from .batch import (
    ANALYZER_PRODUCER,
    ANALYZER_VERSION,
    BatchAnalysisResult,
    BatchTrackResult,
    DEFAULT_PARAMETERS_HASH,
    SignalAnalysisResult,
    SignalAnalyzer,
    analyze_manifest,
    analyze_repository_manifest,
    analyze_track_signal,
    artifact_identity_for_track,
    build_analyzed_track_artifact,
)
from .audio_io import AudioLoadError, DecodedAudio, load_audio
from .cache import (
    ArtifactIdentity,
    CacheError,
    FreshnessDecision,
    LoadedArtifact,
    analyzed_track_path,
    check_analysis_artifact_freshness,
    check_artifact_freshness,
    load_analyzed_artifact,
    load_waveform_artifact,
    track_cache_dir,
    waveform_path,
    write_json_atomic,
)
from .dependencies import DependencyError, OptionalDependencyUnavailable, require_optional_dependency
from .debug_waveform import (
    DEBUG_WAVEFORM_MODE_RGB_BANDS,
    DEFAULT_DEBUG_HIGH_CUTOFF_HZ,
    DEFAULT_DEBUG_LOW_CUTOFF_HZ,
    DEFAULT_DEBUG_WAVEFORM_POINT_COUNT,
    DebugWaveform,
    DebugWaveformError,
    build_debug_waveform_artifact,
    compute_debug_waveform,
    write_debug_waveform_artifact,
)
from .features import (
    DEFAULT_BASS_CUTOFF_HZ,
    DEFAULT_FEATURE_CURVE_POINT_COUNT,
    DEFAULT_FEATURE_FRAME_LENGTH,
    DEFAULT_FEATURE_HOP_LENGTH,
    EnergyFeatures,
    FeatureExtractionError,
    build_energy_analysis,
    compute_energy_features,
)
from .genre import classify_stub
from .manifest import (
    ManifestError,
    RepositoryManifest,
    RepositorySource,
    RepositoryTrack,
    load_repository_manifest,
    parse_repository_manifest,
    resolve_source_path,
)
from .probe import AudioProbe, ProbeError, parse_ffprobe_output, probe_audio
from .rekordbox_xml import (
    REKORDBOX_XML_BACKEND,
    RekordboxCue,
    RekordboxTempo,
    RekordboxTrack,
    RekordboxXmlError,
    apply_rekordbox_overrides,
    apply_rekordbox_xml_file,
    load_rekordbox_track,
)
from .structure import (
    DEFAULT_CUE_SNAP_SECONDS,
    DEFAULT_HIGH_ENERGY_THRESHOLD,
    DEFAULT_LOW_ENERGY_THRESHOLD,
    DEFAULT_MIN_SECTION_SECONDS,
    StructureExtractionError,
    StructureFeatures,
    build_cue_points,
    build_sections,
    compute_structure_features,
)
from .tempo import (
    DEFAULT_TEMPO_HOP_LENGTH,
    DEFAULT_TEMPO_START_BPM,
    FALLBACK_DUBSTEP_BPM,
    NormalizedTempo,
    TempoExtractionError,
    TempoFeatures,
    build_beat_grid,
    build_tempo_analysis,
    compute_tempo_features,
    normalize_dubstep_bpm,
)
from .waveform import (
    DEFAULT_WAVEFORM_POINT_COUNT,
    WAVEFORM_MODE_PEAK_RMS,
    WaveformError,
    WaveformOverview,
    build_waveform_artifact,
    compute_waveform_overview,
    write_waveform_artifact,
)

__all__ = [
    "__version__",
    "analyze_stub",
    "build_analyzed_track_stub",
    "ANALYZER_PRODUCER",
    "ANALYZER_VERSION",
    "BatchAnalysisResult",
    "BatchTrackResult",
    "DEFAULT_PARAMETERS_HASH",
    "SignalAnalysisResult",
    "SignalAnalyzer",
    "analyze_manifest",
    "analyze_repository_manifest",
    "analyze_track_signal",
    "artifact_identity_for_track",
    "build_analyzed_track_artifact",
    "AudioLoadError",
    "DecodedAudio",
    "load_audio",
    "ArtifactIdentity",
    "CacheError",
    "FreshnessDecision",
    "LoadedArtifact",
    "analyzed_track_path",
    "check_analysis_artifact_freshness",
    "check_artifact_freshness",
    "classify_stub",
    "load_analyzed_artifact",
    "load_waveform_artifact",
    "track_cache_dir",
    "waveform_path",
    "write_json_atomic",
    "DependencyError",
    "OptionalDependencyUnavailable",
    "require_optional_dependency",
    "DEBUG_WAVEFORM_MODE_RGB_BANDS",
    "DEFAULT_DEBUG_HIGH_CUTOFF_HZ",
    "DEFAULT_DEBUG_LOW_CUTOFF_HZ",
    "DEFAULT_DEBUG_WAVEFORM_POINT_COUNT",
    "DebugWaveform",
    "DebugWaveformError",
    "build_debug_waveform_artifact",
    "compute_debug_waveform",
    "write_debug_waveform_artifact",
    "DEFAULT_BASS_CUTOFF_HZ",
    "DEFAULT_FEATURE_CURVE_POINT_COUNT",
    "DEFAULT_FEATURE_FRAME_LENGTH",
    "DEFAULT_FEATURE_HOP_LENGTH",
    "EnergyFeatures",
    "FeatureExtractionError",
    "build_energy_analysis",
    "compute_energy_features",
    "ManifestError",
    "RepositoryManifest",
    "RepositorySource",
    "RepositoryTrack",
    "load_repository_manifest",
    "parse_repository_manifest",
    "AudioProbe",
    "ProbeError",
    "parse_ffprobe_output",
    "probe_audio",
    "REKORDBOX_XML_BACKEND",
    "RekordboxCue",
    "RekordboxTempo",
    "RekordboxTrack",
    "RekordboxXmlError",
    "apply_rekordbox_overrides",
    "apply_rekordbox_xml_file",
    "load_rekordbox_track",
    "resolve_source_path",
    "DEFAULT_CUE_SNAP_SECONDS",
    "DEFAULT_HIGH_ENERGY_THRESHOLD",
    "DEFAULT_LOW_ENERGY_THRESHOLD",
    "DEFAULT_MIN_SECTION_SECONDS",
    "StructureExtractionError",
    "StructureFeatures",
    "build_cue_points",
    "build_sections",
    "compute_structure_features",
    "DEFAULT_TEMPO_HOP_LENGTH",
    "DEFAULT_TEMPO_START_BPM",
    "FALLBACK_DUBSTEP_BPM",
    "NormalizedTempo",
    "TempoExtractionError",
    "TempoFeatures",
    "build_beat_grid",
    "build_tempo_analysis",
    "compute_tempo_features",
    "normalize_dubstep_bpm",
    "DEFAULT_WAVEFORM_POINT_COUNT",
    "WAVEFORM_MODE_PEAK_RMS",
    "WaveformError",
    "WaveformOverview",
    "build_waveform_artifact",
    "compute_waveform_overview",
    "write_waveform_artifact",
]
