cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED CONTRACTS_DIR)
    message(FATAL_ERROR "CONTRACTS_DIR must be provided")
endif()

function(read_json_file path out_var)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing JSON file: ${path}")
    endif()

    file(READ "${path}" content)
    string(JSON json_type ERROR_VARIABLE json_error TYPE "${content}")
    if(json_error)
        message(FATAL_ERROR "Invalid JSON in ${path}: ${json_error}")
    endif()
    if(NOT json_type STREQUAL "OBJECT")
        message(FATAL_ERROR "Expected JSON object in ${path}, got ${json_type}")
    endif()

    set("${out_var}" "${content}" PARENT_SCOPE)
endfunction()

function(require_json_string json label)
    string(JSON value ERROR_VARIABLE json_error GET "${json}" ${ARGN})
    if(json_error)
        message(FATAL_ERROR "Missing required string ${label}: ${json_error}")
    endif()
    if(value STREQUAL "")
        message(FATAL_ERROR "Required string ${label} must not be empty")
    endif()
endfunction()

function(require_json_number json label)
    string(JSON value_type ERROR_VARIABLE json_error TYPE "${json}" ${ARGN})
    if(json_error)
        message(FATAL_ERROR "Missing required number ${label}: ${json_error}")
    endif()
    if(NOT value_type STREQUAL "NUMBER")
        message(FATAL_ERROR "Expected ${label} to be NUMBER, got ${value_type}")
    endif()
endfunction()

function(require_array_min_length json label min_length)
    string(JSON array_length ERROR_VARIABLE json_error LENGTH "${json}" ${ARGN})
    if(json_error)
        message(FATAL_ERROR "Missing required array ${label}: ${json_error}")
    endif()
    if(array_length LESS min_length)
        message(FATAL_ERROR "Expected ${label} to contain at least ${min_length} item(s)")
    endif()
endfunction()

function(require_schema_field schema_json schema_label field_name)
    string(JSON required_length ERROR_VARIABLE json_error LENGTH "${schema_json}" required)
    if(json_error)
        message(FATAL_ERROR "Schema ${schema_label} must define a required array: ${json_error}")
    endif()
    if(required_length LESS 1)
        message(FATAL_ERROR "Schema ${schema_label} required array must not be empty")
    endif()

    math(EXPR last_index "${required_length} - 1")
    set(found FALSE)
    foreach(index RANGE 0 ${last_index})
        string(JSON required_field ERROR_VARIABLE item_error GET "${schema_json}" required ${index})
        if(item_error)
            message(FATAL_ERROR "Schema ${schema_label} has invalid required field at ${index}: ${item_error}")
        endif()
        if(required_field STREQUAL "${field_name}")
            set(found TRUE)
        endif()
    endforeach()

    if(NOT found)
        message(FATAL_ERROR "Schema ${schema_label} must require ${field_name}")
    endif()
endfunction()

function(validate_schema path schema_label primary_id)
    read_json_file("${path}" schema_json)
    require_json_string("${schema_json}" "${schema_label} $schema" "\$schema")
    require_json_string("${schema_json}" "${schema_label} $id" "\$id")
    require_schema_field("${schema_json}" "${schema_label}" "schemaVersion")
    require_schema_field("${schema_json}" "${schema_label}" "${primary_id}")
endfunction()

function(require_no_real_audio_paths path)
    file(READ "${path}" content)

    foreach(disallowed IN ITEMS "file://" "/Users/" "/home/" "\\Users\\")
        string(FIND "${content}" "${disallowed}" found_at)
        if(NOT found_at EQUAL -1)
            message(FATAL_ERROR "${path} references a real file path marker: ${disallowed}")
        endif()
    endforeach()

    string(REGEX MATCH "\"[A-Za-z]:[/\\\\]" drive_path_match "${content}")
    if(drive_path_match)
        message(FATAL_ERROR "${path} references a Windows drive path: ${drive_path_match}")
    endif()
endfunction()

set(schemas_dir "${CONTRACTS_DIR}/schemas")
set(examples_dir "${CONTRACTS_DIR}/examples")

set(analyzed_schema "${schemas_dir}/analyzed-track.schema.json")
set(mix_plan_schema "${schemas_dir}/mix-plan.schema.json")
set(repository_schema "${schemas_dir}/repository-manifest.schema.json")

set(analyzed_example "${examples_dir}/analyzed-track.stub.json")
set(mix_plan_example "${examples_dir}/mix-plan.stub.json")
set(repository_example "${examples_dir}/repository-manifest.stub.json")

validate_schema("${analyzed_schema}" "analyzed-track" "trackId")
validate_schema("${mix_plan_schema}" "mix-plan" "planId")
validate_schema("${repository_schema}" "repository-manifest" "repositoryId")

read_json_file("${analyzed_example}" analyzed)
require_json_string("${analyzed}" "analyzed schemaVersion" schemaVersion)
require_json_string("${analyzed}" "analyzed trackId" trackId)
require_json_string("${analyzed}" "analyzed source repositoryId" source repositoryId)
require_json_string("${analyzed}" "analyzed source sourceUri" source sourceUri)
require_json_string("${analyzed}" "analyzed analyzer producer" analyzer producer)
require_json_string("${analyzed}" "analyzed analyzer version" analyzer producerVersion)
require_json_number("${analyzed}" "analyzed durationSeconds" durationSeconds)
require_array_min_length("${analyzed}" "analyzed beatGrid beats" 1 beatGrid beats)
require_array_min_length("${analyzed}" "analyzed sections" 1 sections)
require_array_min_length("${analyzed}" "analyzed cuePoints" 1 cuePoints)
require_no_real_audio_paths("${analyzed_example}")

read_json_file("${mix_plan_example}" mix_plan)
require_json_string("${mix_plan}" "mix plan schemaVersion" schemaVersion)
require_json_string("${mix_plan}" "mix plan planId" planId)
require_json_string("${mix_plan}" "mix plan strategyId" strategy strategyId)
require_array_min_length("${mix_plan}" "mix plan tracks" 1 tracks)
require_array_min_length("${mix_plan}" "mix plan transitions" 1 transitions)
require_array_min_length("${mix_plan}" "mix plan commands" 1 commands)
require_no_real_audio_paths("${mix_plan_example}")

read_json_file("${repository_example}" repository)
require_json_string("${repository}" "repository schemaVersion" schemaVersion)
require_json_string("${repository}" "repository repositoryId" repositoryId)
require_json_string("${repository}" "repository producer" producer)
require_json_string("${repository}" "repository producerVersion" producerVersion)
require_json_string("${repository}" "repository source repositoryType" source repositoryType)
require_array_min_length("${repository}" "repository tracks" 1 tracks)
require_no_real_audio_paths("${repository_example}")
